### PR TITLE
Updated `_hlist-render-child.vm` to address issue #18.

### PR DESCRIPTION
**Pull request by skwlilac**
Suggest fix addressing issue #18 .

### CODE REVIEW

**Comment by simonoakesepimorphics** [comment]
lgtm

**Comment by der** [comment]
It's certainly true that the current code assumes each concept is in a single hierarchy so there's a unique item for entity. That does seem over constraining. There are certainly use cases for collections of items from hierarchies. You wouldn't use a hierarchical view for collections but I can see than when browsing the hierarchy you would also see the references from a collection which is wrong and confusing.

However, I would have expected to just constrain the ?item to be in the same register as the parent. Surely by using `sample` you pick an arbitrary item from any of the referencing registers. Which means that the child presented could well be in a different register which could get very confusing as you navigate further.

I suspect there's something about the use case I'm not understanding.

**Comment by skwlilac** [comment]
This actually came up in trying to 'fit' the NERC NVS data into the registry. They make *very* inconsistent use of SKOS Collections and Concept Schemes. Their use of Collections is straight forward and flat. However, the schemes that the build include terms from the collections and some terms from collections are included in multiple schemes. Certainly not the way that I would have organised things. That said, SKOS itself does not limit a term to being in a single scheme.

I'll take a look at a constraint that the item is in the register to do the filtering instead.

**Comment by skwlilac** [comment]
One problem is in the context of  `main/_hlist-render-child.vm` there is no binding for the register. That would need to be seeded in the setup in `main/_hlist-render-as-tree.vm`

**Comment by skwlilac** [comment]
@der I've taken on your suggestion of using register membership to eliminate duplicates rather than making a random pick. It was a little more involved to implement because I need to add an additional querty parameter to propagate the register URI through the progressive expansion of the tree,

**Comment by der** [comment]
Not sure why the explicit passing is needed. Surely this partial template is being run within the context of `_render-register-as-tree.vm` so we already know the register we are displaying?

Don't object to it, just wasn't expecting to need it.

**Comment by skwlilac** [comment]
@der Neither was I (expecting to need it) until I tried.  As I understand the template code, the expansion step is queued by a callback link like this:

```html
<a href="#" data-state="new" data-target="$uiroot/main/_hlist-render-child?concept=$lib.pathEncode($member.uRI)&narrow=$lib.pathEncode($narrow)&reg=$lib.pathEncode($reg)" class="hlist-button"><span class="glyphicon glyphicon-plus-sign"></span></a>
```
which reaches straight into `main/_hlist-render-child` without passing through anything that has previously set up a value for `$register`. 

Happy to use something more direct if there is a better way.

**Comment by der** [comment]
Ah yes, sorry, you are quite right. At it passes the parent concept not the item so any traversal from there up the register would be equally as ambiguous as for the child.

**Comment by skwlilac** [comment]
Absent any further response from @simonoakesepimorphics or @alexrcoley I'll merge this tomorrow. No requirement to speak, just having tagged you as reviews wanted to give you a reasonable chance to respond.

**Pull request merged**
